---
# See: https://docs.ansible.com/ansible/latest/collections/community/general/snap_module.html
- name: Install Canonical microcloud
  remote_user: woakley
  become: yes
  hosts: all

  tasks:

  - name: install lxd snap pkg
    community.general.snap:
      name: lxd 
      channel: 5.21/stable

  - name: install microceph snap pkg
    community.general.snap:
      name: microceph
      channel: quincy/stable

  - name: install microovn snap pkg
    community.general.snap:
      name: microovn 
      channel: 22.03/stable

  - name: install microcloud snap pkg
    community.general.snap:
      name: microcloud
      channel: latest/stable
